### ISSUE TITLE
Add an option to show a "new file" button

### ISSUE THREAD

**Issue by dkniffin** [cdonohue/flexible-ui#3]
I love this theme, and how it matches my current syntax theme. I also really like how this theme fills up the entire space in the tab bar. However, I'd like a button on the right or something that allows me to quickly create a new file. For an example of this, take a look at chrome's tab bar.

**Comment by cdonohue** [comment]
Thanks for the kind words @dkniffin! I've actually started focusing on https://github.com/cdonohue/pristine-ui, which retains most of the ideas and adaptability that this theme has. It also has a few other nice features, like different layout modes and tab sizes.

As for a quick way to create a new file, have you tried https://atom.io/packages/advanced-open-file? I use that package quite a bit, and it works for _both_ opening and creating.

Or, if you'd rather use the mouse, check this package out: 

> https://atom.io/packages/new-tab
