### ISSUE TITLE
Selection bug in 1.13.0

### ISSUE THREAD

**Issue by dkniffin** [cdonohue/flexible-ui#4]
I've just upgraded to Atom 1.13.0, and started getting this bug:

![](http://g.recordit.co/VRfSAJZ8LQ.gif)

It's hard to describe, but basically when I highlight something (or the editor does it for me, in the case of highlighting open/close parens), the code moves around under my cursor.

I'm pretty sure the issue is some sort of incompatibility between this package and 1.13.0, because I don't have this issue with other UI themes.

**Comment by cdonohue** [comment]
This is fixed with https://github.com/cdonohue/flexible-ui/pull/5
