### ISSUE TITLE
Font of the image (sorry about this)

### ISSUE THREAD

**Issue by casssiahaluu** [cdonohue/flexible-ui#6]
![image](https://user-images.githubusercontent.com/11221993/30466369-ba0ea420-99b3-11e7-9d7c-fbbefafe7e81.png)
Please. Tell me. What's the name of  cursive font of the image? I'm searching a good cursive font for weeks and not found nothing. But this font is perfect!

Hey, by the way. This theme is very beautiful. I like this [Pristine UI](https://atom.io/themes/pristine-ui) too :smile:

**Comment by cdonohue** [comment]
@HaluDeCassia the font used here (both regular _and_ italics) is [Operator Mono](https://www.typography.com/fonts/operator/styles/operatormonoscreensmart). Glad you like the UI themes!

**Comment by casssiahaluu** [comment]
@cdonohue thanks! :smile:
